feat(backend): added build & deploy composite
kitabisa/composite-actions pull request #28
Opened 2022-12-22 03:29 UTC by sactioswastioyono18

Tested in suramadu
https://github.com/kitabisa/suramadu/actions/runs/3754637352/jobs/6379035246

2022-12-22 04:36 UTC, dmzrio requested changes

2022-12-22 04:36 UTC, dmzrio commented on build/backend/action.yaml
> +    default: "^1.13.1"
@sactioswastioyono18 ini di tambahin newline y mas kyk input yg di backend/action.yaml.

2022-12-22 04:36 UTC, dmzrio commented on build/backend/action.yaml
> +
Tambahin ini ya mas, buat setup gcloud sma buildx
```
    - name: Setup gcloud
      uses: kitabisa/composite-actions/packages/gcloud@main
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Setup docker buildx
      uses: kitabisa/composite-actions/packages/buildx@main
      with:
        project_id: ${{ inputs.project_id }}
        gcr_host: ${{ inputs.gcr_host }}
        cache: ${{ inputs.cache }} 

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
```

2022-12-22 04:36 UTC, dmzrio commented on build/backend/action.yaml
> +        make build
ini di ganti sama ini y mas

    - name: Build push
      id: build-push
      uses: kitabisa/composite-actions/packages/makefile@main
      with:
        project_id: ${{ inputs.project_id }}
        gcr_host: ${{ inputs.gcr_host }}
        chartmuseum_host: ${{ inputs.chartmuseum_host }}
        chartmuseum_user: ${{ inputs.chartmuseum_user }}
        chartmuseum_pass: ${{ inputs.chartmuseum_pass }}
        build: true
        package: true

2022-12-22 04:36 UTC, dmzrio commented on build/backend/action.yaml
> +
Tambahan input.

```
  project_id:
    required: true
    description: "GCP project id"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gcr_host:
    required: true
    description: "GCP container registry host"
    type: string

  chartmuseum_host:
    required: true
    description: "ChartMuseum host"
    type: string


  chartmuseum_user:
    required: true
    description: "ChartMuseum user"
    type: string


  chartmuseum_pass:
    required: true
    description: "ChartMuseum password"
    type: string
```

2022-12-22 04:36 UTC, dmzrio commented on deploy/backend/action.yaml
> +  steps:
Tambahan checkout.
```
    - name: Checking out repository
      uses: actions/checkout@v3
```

2022-12-22 04:36 UTC, dmzrio commented on deploy/backend/action.yaml
> +        gcr_host: ${{ inputs.gcr_host }}
ini bisa di hapus ya mas, soalnya udh g perlu build.

2022-12-22 05:51 UTC, sactioswastioyono18 commented on build/backend/action.yaml
> +
kalo cachingnya, di action go v3 uda ada parameter cachenya mas jadi ga perlu pake `actions/cache` dan dia bisa targetin `go.sum` juga dimana

terus klo build ini kan concernya cuma buat build aja, kayaknya ga perlu setup docker, ya ga sih?

jadi bisa di reuse untuk ngetrigger coverage (unit test)

hanya di bagian deploy aja kita perlu ngetrigger action docker buat di push kan imagenya?

2022-12-22 05:51 UTC, sactioswastioyono18 commented on build/backend/action.yaml
> +        make build
ini klo dia package brarti klo dipake buat unit test aja, dia akan tetep ngepush dong ya?

2022-12-22 05:54 UTC, sactioswastioyono18 commented
Jadi ini approachnya kayaknya kita pengen pisahin `build` ama `deploy` yang mana build ini bisa direuse juga oleh workflow untuk unit test

nah karena unit test ga perlu build docker dan push ke gcr, jadi build literally hanya build aja 
klo mau build deploy, ya kita panggil compose build + deploynya, jadi lebih `tercompose` & single responsibility 

gimana menurut mas @dimzrio ?

2022-12-23 02:52 UTC, sactioswastioyono18 commented on build/backend/action.yaml
> +    default: "^1.13.1"
done

2022-12-23 02:59 UTC, sactioswastioyono18 commented
Kurefactor jadinya pas bagian build ada nerima parameter `build-push-image` ya

jadi bagian deploynya pure deploy aja
bagian buildnya klo parameter push true, baru dia ngepush image
dan bisa di reuse buat build test jg

2022-12-23 05:59 UTC, dmzrio commented
> Kurefactor jadinya pas bagian build ada nerima parameter `build-push-image` ya
> 
> jadi bagian deploynya pure deploy aja bagian buildnya klo parameter push true, baru dia ngepush image dan bisa di reuse buat build test jg

ah baru nangkep context nya. sory2, kmrin asumsi w perlakuannya kyk composite nya frontend. kg baca detail desc PR nya..haha
ok deh mas, di tambahin input `build-push-image` aja. jadi composite nya bisa di pake ketika test sma build-push k gcr. mantaps2

2022-12-23 06:07 UTC, dmzrio approved these changes

2022-12-23 09:28 UTC, merged